name: CI Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  pixi-check:
    name: Pixi Environment & Lockfile Check
    runs-on: ubuntu-latest

    steps:
      - name: Download Repository on Ubuntu VM
        uses: actions/checkout@v4

      - name: Install Pixi and Verify Lockfile Integrity
        uses: prefix-dev/setup-pixi@v0.10.0
        with:
          pixi-version: v0.73.0
          locked: true

  trufflehog-check:
    name: Secret & Credential Leak Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog-main-action@main
